name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prune
        run: npm prune --production

      - name: Zip
        run: |
          zip -r lambda.zip node_modules/*
          zip -g -j lambda.zip build/*

      - name: Save package artifact
        uses: actions/upload-artifact@v3
        with:
          name: lambda
          path: lambda.zip